# Generated by Django 2.1 on 2018-10-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='registereduser_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='registereduser_ptr',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
