# Generated by Django 2.1 on 2018-10-11 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20181011_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='enrolled_user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='classroom',
            name='enrolled_users',
            field=models.ManyToManyField(
                related_name='enrolled_classrooms',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='classrooms',
                to='cms.Course'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='owned_classrooms',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='period',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='classrooms',
                to='cms.Period'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='cms.Project'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='comments',
                to='cms.CustomUser'),
        ),
        migrations.AlterField(
            model_name='project',
            name='classroom',
            field=models.ManyToManyField(
                related_name='projects',
                to='cms.Classroom'),
        ),
    ]
